
use customer_behavior

select top 5 *
from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as 'Total'
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select AVG(purchase_amount)
from customer

select customer_id
from customer
where discount_applied like 'Yes' and purchase_amount > (select AVG(purchase_amount)
														from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,AVG(review_rating) as 'averageReR'
from customer
group by item_purchased
order by averageReR DESC

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,avg(purchase_amount) as 'avg amount'
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,AVG(purchase_amount) as 'avg',SUM(purchase_amount) as 'sum'
from customer
group by subscription_status
